name: CI

on: 
  push:
    branches:
      - '**'

  workflow_dispatch:

  workflow_call:

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Test
        run: npm test

      - name: Lint
        run: npx gulp lint

      - name: Build
        run: npx gulp build
