name: Trigger release on merge
run-name: Starting release for ${{ github.actor }} PR merge
on:
  pull_request_target:
    types:
      - closed
    branches:
      - develop

jobs:
  verify-changelog:
    if: github.event.pull_request.merged == true
    outputs:
      HAS_CHANGELOG: ${{ steps.ensure-changelog.outputs.HAS_CHANGELOG }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ensure Changelog
      id: ensure-changelog
      shell: bash
      run: |
        changes=$(gh pr view ${{github.event.pull_request.number}} --json files -q '.files[].path')
        if echo $changes | grep -q CHANGELOG.md; then
          echo "CHANGELOG.md has been updated"
          echo "HAS_CHANGELOG=true" >> $GITHUB_OUTPUT
        else
          echo "CHANGELOG.md has not been updated, skipping release"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-ui-release:
    needs: verify-changelog
    if: ${{ needs.verify-changelog.outputs.HAS_CHANGELOG }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}
          ref: develop

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Read package.json version
        uses: actions/github-script@v6
        id: define-package-json-version
        with:
          script: |
            const { version } = require('./package.json')
            core.setOutput('packageJsonVersion', version)

      - name: Detect release level from changelog
        uses: actions/github-script@v6
        id: detect-release-level
        with:
          script: |
            const { detectReleaseLevel } = require('./.github/scripts/detectReleaseLevel.js');
            
            try {
              const releaseLevel = detectReleaseLevel(core);
              core.setOutput('release_level', releaseLevel);
              return releaseLevel;
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Define release version
        uses: actions/github-script@v6
        id: define-release-version
        with:
          script: |
            const { defineReleaseVersion } = require('./.github/scripts/defineVersion.js');
            const releaseLevel = '${{ steps.detect-release-level.outputs.release_level }}';
            const currentVersion = '${{ steps.define-package-json-version.outputs.packageJsonVersion }}';
            
            return defineReleaseVersion({core}, releaseLevel, currentVersion);

      - name: Trigger release
        uses: ./.github/workflows/release.yml
        with:
          version_number: ${{ fromJson(steps.define-release-version.outputs.result).full }}
          release_type: final
          branch_name: develop
        secrets:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GCS_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
          RELEASE_SUCCESS_SLACK_WEBHOOK: ${{ secrets.RELEASE_SUCCESS_SLACK_WEBHOOK }}
          RELEASE_FAILURE_SLACK_WEBHOOK: ${{ secrets.RELEASE_FAILURE_SLACK_WEBHOOK }}
