name: Trigger release on merge
run-name: Starting release for ${{ github.actor }} PR merge
on:
  pull_request_target:
    types:
      - closed
    branches:
      - develop
      - support/*

concurrency:
  group: continuous-deployment-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: true

jobs:
  verify-changelog:
    name: Verify that CHANGELOG.md has been updated
    if: github.event.pull_request.merged == true
    outputs:
      HAS_CHANGELOG: ${{ steps.ensure-changelog.outputs.HAS_CHANGELOG }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ensure Changelog
      id: ensure-changelog
      shell: bash
      run: |
        changes=$(gh pr view ${{github.event.pull_request.number}} --json files -q '.files[].path')
        if echo $changes | grep -q CHANGELOG.md; then
          echo "CHANGELOG.md has been updated"
          echo "HAS_CHANGELOG=true" >> $GITHUB_OUTPUT
        else
          echo "CHANGELOG.md has not been updated, skipping release"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prepare-version:
    name: Detect and build the version number for the release
    needs: verify-changelog
    if: ${{ needs.verify-changelog.outputs.HAS_CHANGELOG }}
    outputs:
      version_number: ${{ steps.define-release-version.outputs.version_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Read package.json version
        uses: actions/github-script@v6
        id: define-package-json-version
        with:
          script: |
            const { version } = require('./package.json')
            core.setOutput('packageJsonVersion', version)

      - name: Detect release level from changelog
        uses: actions/github-script@v6
        id: detect-release-level
        with:
          script: |
            const { detectReleaseLevel } = require('./.github/scripts/detectReleaseLevel.js');
            
            try {
              const releaseLevel = detectReleaseLevel(core);
              core.setOutput('release_level', releaseLevel);
              return releaseLevel;
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Define release version
        uses: actions/github-script@v6
        id: define-release-version
        with:
          script: |
            const { defineReleaseVersion } = require('./.github/scripts/defineVersion.js');
            const releaseLevel = '${{ steps.detect-release-level.outputs.release_level }}';
            const currentVersion = '${{ steps.define-package-json-version.outputs.packageJsonVersion }}';
            
            const result = defineReleaseVersion({core}, releaseLevel, currentVersion);
            core.setOutput('version_number', result.full);

  release:
    needs: [prepare-version]
    name: Trigger release
    uses: ./.github/workflows/release.yml
    with:
      version_number: ${{ needs.prepare-version.outputs.version_number }}
      release_type: final
      branch_name: ${{ github.event.pull_request.base.ref }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      GCS_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
